-- 投入先のDBを指定;
CONNECT TO SAMPLE2;
-- 一般ユーザのスキーマを指定;
SET SCHEMA sample;
CREATE TABLE BUSINESS_DATE (
  SEGMENT_ID CHAR NOT NULL ,
  BIZ_DATE CHAR NOT NULL
);
CREATE TABLE CODE_NAME (
  CODE_ID CHAR NOT NULL ,
  CODE_VALUE VARCHAR(2) NOT NULL ,
  LANG CHAR NOT NULL ,
  SORT_ORDER INT NOT NULL ,
  CODE_NAME VARCHAR(50) NOT NULL ,
  SHORT_NAME VARCHAR(50) NULL ,
  OPTION01 VARCHAR(50) NULL ,
  OPTION02 VARCHAR(50) NULL ,
  OPTION03 VARCHAR(50) NULL ,
  OPTION04 VARCHAR(50) NULL ,
  OPTION05 VARCHAR(50) NULL ,
  OPTION06 VARCHAR(50) NULL ,
  OPTION07 VARCHAR(50) NULL ,
  OPTION08 VARCHAR(50) NULL ,
  OPTION09 VARCHAR(50) NULL ,
  OPTION10 VARCHAR(50) NULL
);
CREATE TABLE CODE_PATTERN (
  CODE_ID CHAR NOT NULL ,
  CODE_VALUE VARCHAR(2) NOT NULL ,
  PATTERN01 CHAR NOT NULL ,
  PATTERN02 CHAR NULL ,
  PATTERN03 CHAR NULL ,
  PATTERN04 CHAR NULL ,
  PATTERN05 CHAR NULL ,
  PATTERN06 CHAR NULL ,
  PATTERN07 CHAR NULL ,
  PATTERN08 CHAR NULL ,
  PATTERN09 CHAR NULL ,
  PATTERN10 CHAR NULL ,
  PATTERN11 CHAR NULL ,
  PATTERN12 CHAR NULL ,
  PATTERN13 CHAR NULL ,
  PATTERN14 CHAR NULL ,
  PATTERN15 CHAR NULL ,
  PATTERN16 CHAR NULL ,
  PATTERN17 CHAR NULL ,
  PATTERN18 CHAR NULL ,
  PATTERN19 CHAR NULL ,
  PATTERN20 CHAR NULL
);
CREATE TABLE SAMPLE_USER (
  USER_ID VARCHAR(20) NOT NULL ,
  FAMILY_NAME VARCHAR(20) NOT NULL ,
  FIRST_NAME VARCHAR(20) NOT NULL
);
CREATE TABLE SAMPLE_USER_ERROR (
  LINE_NUMBER BIGINT NOT NULL ,
  USER_ID VARCHAR(20) NOT NULL ,
  FAMILY_NAME VARCHAR(20) NOT NULL ,
  FIRST_NAME VARCHAR(20) NOT NULL
);
CREATE TABLE SAMPLE_USER_WORK (
  LINE_NUMBER BIGINT NOT NULL ,
  USER_ID VARCHAR(20) NOT NULL ,
  FAMILY_NAME VARCHAR(20) NOT NULL ,
  FIRST_NAME VARCHAR(20) NOT NULL
);
ALTER TABLE BUSINESS_DATE
ADD CONSTRAINT PK_BUSINESS_DATE1 PRIMARY KEY
(
  SEGMENT_ID
);
ALTER TABLE SAMPLE_USER_WORK
ADD CONSTRAINT PK_SAMPLE_USER1 PRIMARY KEY
(
  LINE_NUMBER
);
ALTER TABLE SAMPLE_USER
ADD CONSTRAINT PK_SAMPLE_USER_INFO PRIMARY KEY
(
  USER_ID
);
ALTER TABLE SAMPLE_USER_ERROR
ADD CONSTRAINT PK_SAMPLE_USER_WORK1 PRIMARY KEY
(
  LINE_NUMBER
);
ALTER TABLE CODE_PATTERN
ADD CONSTRAINT SYS_C0058550 PRIMARY KEY
(
  CODE_ID,
  CODE_VALUE
);
ALTER TABLE CODE_NAME
ADD CONSTRAINT SYS_C0058560 PRIMARY KEY
(
  CODE_ID,
  CODE_VALUE,
  LANG
);
ALTER TABLE CODE_NAME
ADD
FOREIGN KEY (
  CODE_ID,
  CODE_VALUE
) REFERENCES CODE_PATTERN (
  CODE_ID,
  CODE_VALUE
);
