DROP TABLE USER_SESSION CASCADE CONSTRAINTS PURGE;
DROP TABLE CODE_PATTERN CASCADE CONSTRAINTS PURGE;
DROP TABLE CODE_NAME CASCADE CONSTRAINTS PURGE;
DROP TABLE DOUBLE_SUBMISSION CASCADE CONSTRAINTS PURGE;
