DROP TABLE CODE_NAME CASCADE CONSTRAINTS PURGE;
DROP TABLE CODE_PATTERN CASCADE CONSTRAINTS PURGE;
DROP TABLE SAMPLE_USER CASCADE CONSTRAINTS PURGE;
DROP TABLE SAMPLE_USER_WORK CASCADE CONSTRAINTS PURGE;
DROP TABLE SAMPLE_USER_ERROR CASCADE CONSTRAINTS PURGE;
DROP TABLE BUSINESS_DATE CASCADE CONSTRAINTS PURGE;
