DROP TABLE CODE_NAME CASCADE;
DROP TABLE CODE_PATTERN CASCADE;
DROP TABLE SAMPLE_USER CASCADE;
DROP TABLE SAMPLE_USER_WORK CASCADE;
DROP TABLE SAMPLE_USER_ERROR CASCADE;
DROP TABLE BUSINESS_DATE CASCADE;
